# Generated by Django 5.1.2 on 2025-09-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monasteries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monastery',
            name='virtual_tour_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
