# Generated by Django 5.2.5 on 2025-09-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monasteries', '0002_monastery_virtual_tour_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='monastery',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monastery',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
