# Generated by Django 5.2.5 on 2025-09-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monasteries', '0003_monastery_latitude_monastery_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='archives/')),
                ('category', models.CharField(choices=[('manuscript', 'Manuscript'), ('mural', 'Mural'), ('thangka', 'Thangka Painting'), ('relic', 'Relic'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='monasteries.monastery')),
            ],
        ),
    ]
