# Generated by Django 5.2.5 on 2025-09-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monasteries', '0005_monk_monksession_monksessionapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonasteryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('prayer_hall', 'Prayer Hall'), ('meditation_room', 'Meditation Room'), ('library', 'Library'), ('shrine_room', 'Shrine Room'), ('courtyard', 'Courtyard'), ('entrance', 'Entrance'), ('corridor', 'Corridor'), ('garden', 'Garden'), ('dining_hall', 'Dining Hall'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_main_entrance', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('monastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='monasteries.monastery')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonasteryPanorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='monastery_panoramas/')),
                ('is_primary', models.BooleanField(default=False)),
                ('heading', models.IntegerField(default=0, help_text='Initial viewing direction (0-360 degrees)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='monasteries.monasteryroom')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonasteryHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_type', models.CharField(choices=[('navigation', 'Navigation to Another Room'), ('info', 'Information Point'), ('audio', 'Audio Description'), ('zoom', 'Zoom View'), ('video', 'Video Content')], default='info', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('x_position', models.FloatField(help_text='Horizontal position (0-100%)')),
                ('y_position', models.FloatField(help_text='Vertical position (0-100%)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='monastery_audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='monastery_videos/')),
                ('info_image', models.ImageField(blank=True, null=True, upload_to='monastery_info/')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='monasteries.monasterypanorama')),
                ('target_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monasteries.monasteryroom')),
            ],
        ),
    ]
