# Generated by Django 5.2.5 on 2025-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monasteries', '0006_monasteryroom_monasterypanorama_monasteryhotspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonasteryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='monastery_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='monasterypanorama',
            name='room',
        ),
        migrations.RemoveField(
            model_name='monasteryroom',
            name='monastery',
        ),
        migrations.DeleteModel(
            name='MonasteryHotspot',
        ),
        migrations.DeleteModel(
            name='MonasteryPanorama',
        ),
        migrations.DeleteModel(
            name='MonasteryRoom',
        ),
    ]
