# Generated by Django 5.2.5 on 2025-09-19 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monasteries', '0007_monasteryimage_remove_monasterypanorama_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonasteryVirtualTourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='monastery_virtual_tours/')),
                ('monastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tour_images', to='monasteries.monastery')),
            ],
        ),
        migrations.DeleteModel(
            name='MonasteryImage',
        ),
    ]
