# Generated by Django 5.2.5 on 2025-09-19 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monasteries', '0008_monasteryvirtualtourimage_delete_monasteryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('monastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monasteries.monastery')),
            ],
        ),
    ]
