# Generated by Django 5.2.5 on 2025-09-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monasteries', '0009_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
